//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasparCgPlayer.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasparCgPlayer.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///										xmlns:v=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///		&lt;v:String x:Key=&quot;m_Main_title&quot;&gt;CasparCG Player&lt;/v:String&gt;
        ///		&lt;v:String x:Key=&quot;m_Settings_title&quot;&gt;Settings&lt;/v:String&gt;
        ///		&lt;v:String x:Key=&quot;m_Settings_tooltip&quot;&gt;Open the Settings window&lt;/v:String&gt;
        ///		&lt;v:String x:Key=&quot;m_menu_Language&quot;&gt;Language&lt;/v:String&gt;
        ///&lt;/ResourceDictionary&gt;.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///										xmlns:v=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///		&lt;v:String x:Key=&quot;m_Main_title&quot;&gt;CasparCG Player&lt;/v:String&gt;
        ///		&lt;v:String x:Key=&quot;m_Settings_title&quot;&gt;Настройки&lt;/v:String&gt;
        ///		&lt;v:String x:Key=&quot;m_Settings_tooltip&quot;&gt;Открыть окно с настройками приложения&lt;/v:String&gt;
        ///		&lt;v:String x:Key=&quot;m_menu_Language&quot;&gt;Язык приложения&lt;/v:String&gt;
        ///&lt;/ResourceDicti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ru_RU {
            get {
                return ResourceManager.GetString("lang_ru_RU", resourceCulture);
            }
        }
    }
}
